-- MySQL Script generated by MySQL Workbench
-- 02/08/17 15:58:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ParagonMLS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ParagonMLS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ParagonMLS` DEFAULT CHARACTER SET utf8 ;
USE `ParagonMLS` ;

-- -----------------------------------------------------
-- Table `ParagonMLS`.`Agencies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ParagonMLS`.`Agencies` (
  `agency_id` INT NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(100) NULL,
  `phone_number` VARCHAR(14) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(2) NULL,
  `zip` VARCHAR(12) NULL,
  `address` VARCHAR(100) NULL,
  PRIMARY KEY (`agency_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ParagonMLS`.`Agents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ParagonMLS`.`Agents` (
  `agent_id` INT NOT NULL AUTO_INCREMENT,
  `Agencies_agency_id` INT NOT NULL,
  `user_login` VARCHAR(100) NULL,
  `password` VARCHAR(100) NULL,
  `first_name` VARCHAR(100) NULL,
  `last_name` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `phone_number` VARCHAR(14) NULL,
  PRIMARY KEY (`agent_id`),
  INDEX `fk_Agents_Agencies1_idx` (`Agencies_agency_id` ASC),
  CONSTRAINT `fk_Agents_Agencies1`
    FOREIGN KEY (`Agencies_agency_id`)
    REFERENCES `ParagonMLS`.`Agencies` (`agency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ParagonMLS`.`Listings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ParagonMLS`.`Listings` (
  `MLS_number` INT NOT NULL AUTO_INCREMENT,
  `Agents_listing_agent_id` INT NOT NULL,
  `price` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `zip` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `square_footage` VARCHAR(45) NULL,
  `number_of_bedrooms` VARCHAR(45) NULL,
  `number_of_bathrooms` VARCHAR(45) NULL,
  `room_desc` VARCHAR(45) NULL,
  `listing_desc` VARCHAR(45) NULL,
  `additional_info` VARCHAR(45) NULL,
  PRIMARY KEY (`MLS_number`),
  INDEX `fk_Listings_Agents1_idx` (`Agents_listing_agent_id` ASC),
  CONSTRAINT `fk_Listings_Agents1`
    FOREIGN KEY (`Agents_listing_agent_id`)
    REFERENCES `ParagonMLS`.`Agents` (`agent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ParagonMLS`.`Showings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ParagonMLS`.`Showings` (
  `showing_id` INT NOT NULL AUTO_INCREMENT,
  `Listings_MLS_number` INT NOT NULL,
  `Agents_showing_agent_id` INT NOT NULL,
  `start_time` VARCHAR(45) NULL,
  `end_time` VARCHAR(45) NULL,
  `date` VARCHAR(45) NULL,
  PRIMARY KEY (`showing_id`),
  INDEX `fk_Showings_Listings1_idx` (`Listings_MLS_number` ASC),
  INDEX `fk_Showings_Agents1_idx` (`Agents_showing_agent_id` ASC),
  CONSTRAINT `fk_Showings_Listings1`
    FOREIGN KEY (`Listings_MLS_number`)
    REFERENCES `ParagonMLS`.`Listings` (`MLS_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Showings_Agents1`
    FOREIGN KEY (`Agents_showing_agent_id`)
    REFERENCES `ParagonMLS`.`Agents` (`agent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
